ACCOUNT_AUTHENTICATION_METHOD =['username', 'email', 'username_email'][2]
ACCOUNT_EMAIL_VERIFICATION = ["none", "mandatory", "optional"][2]
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 3
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 900  # 15 minutes
ACCOUNT_EMAIL_MAX_LENGTH = 100
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_USERNAME_MIN_LENGTH = 5

# read doc at https://django-allauth.readthedocs.io/