# Generated by Django 4.1.7 on 2023-04-03 13:18

from django.db import migrations, models
import storerecipe.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=storerecipe.utils.media.get_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                choices=[("married", "Married"), ("single", "Single")],
                default="single",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="female",
                max_length=30,
            ),
        ),
    ]
