# Generated by Django 4.1.7 on 2023-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stave",
            name="reply",
            field=models.ManyToManyField(
                null=True, related_name="stave_replies", to="stave.stave"
            ),
        ),
    ]
