# Generated by Django 4.1.7 on 2023-04-03 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stave", "0002_stave_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stave",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="stave_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="stave",
            name="reply",
            field=models.ManyToManyField(
                blank=True, related_name="stave_replies", to="stave.stave"
            ),
        ),
    ]
